### ISSUE TITLE
cellar gray door

### ISSUE THREAD

**Issue by randorandy** [SubversionRando/SubversionRando#18]
Considering having the cellar gray door become a flashing gray door for area rando... we have the technology, I would just have to go pursue that. It shouldn't affect logic at all, just removing a potential softlock.

**Comment by randorandy** [comment]
I suppose that does change the casual logic to remove the need for darkvisor in casual area rando

**Comment by beauxq** [comment]
fixed by https://github.com/SubversionRando/SubversionRando/commit/9e6f8b77bf0c025ed7bd03a8d0d261433fc6ab1b
