### ISSUE TITLE
Impossible Seed: Super Missiles Locked into Suzi Island: Obscured Vestibule

### ISSUE THREAD

**Issue by TheyCallMeXander** [SubversionRando/SubversionRando#7]
[SubCS7021840.sfc.spoiler.txt](https://github.com/SubversionRando/SubversionRando/files/10058441/SubCS7021840.sfc.spoiler.txt)

Enclosed is the spoiler text for the Randomizer which i downloaded to test the morning of 11/21/2022

**Comment by randorandy** [comment]
Thanks, I am aware that suzi island was improperly connected with migrating all logic into area logic. I appreciate the report! I don't know the exact dates of when that switch happened, but I imagine it's the version after logicAreaExpert went out of favor and logicExpert contained the area transitions inside.

**Comment by randorandy** [comment]
still doing a massive logic update which will include the correction that caused your error
