### ISSUE TITLE
non-area doors

### ISSUE THREAD

**Issue by randorandy** [SubversionRando/SubversionRando#8]
Non-area rando doors are still the original colors while playing, and this needs to be reflected in the logic for those particular doors. Currently, migrating the non-area logic to area logic does not account for these doors needing to be opened. I may need to reconsider a lot of sky locations because of this because WestTerminalAccess is kind of a "starting point" for many of these locations. FoyerR is also a starting point for many pirate lab locations.
I believe the full list is:
CraterR (PB)
WestTerminalAccessL (PB)
VulnarCanyonL (PB)
FoyerR (Super)

**Comment by beauxq** [comment]
I'm imaging logic that looks something like this.


```python
        ("SunkenNestL", "CraterR"): lambda loadout: (
            loadout.has_all(canFly, canOpen(CraterR))
        ),
```

The `canOpen` function would return a logic shortcut that could handle what we need based on area rando or not.

I think this would also kind of pave the way for doorcap rando, later on.

What do you think?

**Comment by randorandy** [comment]
That can work. I am not feeling like rewriting every bit of logic to consider every colored door at the moment, but for these four it should be a good solution.

**Comment by beauxq** [comment]
`canOpen` can be used with those 4 doors now

`canOpen(VulnarCanyonL) in  loadout`
`loadout.has_all(canOpen(FoyerR))`
